PYTHON_API_DIR = 'D:/repos/darwin-api/PYTHON'
DWX_FTP_USER = 'ShinyPants'
DWX_FTP_PASS = 'B7A5jZlyaKn3wo'
DWX_FTP_HOSTNAME = 'tickdata.darwinex.com'
TICK_DATA_PATH = 'D:/data/dwx/tick'
MINUTE_DATA_PATH = 'D:/data/dwx/minute'
HOUR_DATA_PATH = 'D:/data/dwx/hour'

DAWRINEX_TICKERS = ['AUDCHF', 'AUDJPY', 'AUDNZD', 'AUDUSD', 'AUS200', 'CADCHF', 'CADJPY', 'CHFJPY', 
    'EURAUD', 'EURCAD', 'EURCHF', 'EURGBP', 'EURJPY', 'EURMXN', 'EURNOK', 'EURNZD', 'EURSEK', 'EURSGD', 'EURTRY', 'EURUSD',
    'FCHI', 'GBPAUD', 'GBPCAD', 'GBPCHF', 'GBPJPY', 'GBPMXN', 'GBPNOK', 'GBPNZD', 'GBPSEK', 'GBPTRY', 'GBPUSD', 'GDAXIm',
    'GDAXIm', 'J225', 'NDXm', 'NZDCAD', 'NZDCHF', 'NZDJPY', 'NZDUSD', 'SPN35', 'SPXm', 'STOXX50E',
    'UK100', 'USDCAD', 'USDCHF', 'USDHKD', 'USDJPY', 'USDMXN', 'USDNOK', 'USDSEK', 'USDSGD', 'USDTRY',
    'WS30', 'XAGUSD', 'XAUUSD', 'XBNUSD', 'XBTUSD', 'XETUSD', 'XLCUSD', 'XNGUSD', 'XPDUSD', 'XPTUSD', 'XRPUSD', 'XTIUSD'
]

RW_TICKERS = [
    'USDZAR', 'USDTRY', 'USDSGD', 'USDSEK', 'USDRUB', 'USDNOK', 'USDMXN', 'USDJPY', 'USDCHF', 'USDCAD', 'USDBRL',
    'NZDUSD', 'NZDJPY', 'NZDCHF', 'NZDCAD', 'HKDUSD', 
    'GBPUSD', 'GBPTRY', 'GBPSEK',' GBPNZD', 'GBPNOK', 'GBPMXN', 'GBPJPY', 'GBPCHF', 'GBPCAD', 'GBPAUD',
    'EURZAR', 'EURUSD', 'EURTRY', 'EURSEK', 'EURPLN', 'EURNZD', 'EURNOK', 'EURMXN', 'EURJPY', 'EURHKD', 'EURGBP', 'EURDKK', 'EURCHF', 'EURCAD', 'EURAUD',
    'CHFJPY', 'CADJPY', 'CADCHF',
    'AUDUSD', 'AUDNZD', 'AUDJPY', 'AUDCHF', 'AUDCAD'
]

G8_TICKERS = ['AUDCAD', 'AUDCHF', 'AUDJPY', 'AUDNZD', 'AUDUSD',
    'CADCHF', 'CADJPY', 'CHFJPY',
    'EURAUD', 'EURCAD', 'EURCHF', 'EURGBP', 'EURJPY', 'EURNZD', 'EURUSD',
    'GBPAUD', 'GBPCAD', 'GBPCHF', 'GBPJPY', 'GBPNZD', 'GBPUSD',
    'NZDCAD', 'NZDCHF', 'NZDJPY', 'NZDUSD',
    'USDCAD', 'USDCHF', 'USDJPY' 
]


INTRADAY_TICKERS = {
    "EURAUD", "EURCHF", "EURNZD", "EURUSD", "GBPUSD", "USDCHF", "USDJPY"
}